#!/home/v-perlbrew/perl5/perlbrew/bin/perl
use 5.010;
use strict;
use warnings;
use Net::FCP::Tiny;

given ($ARGV[0]) {
    when ("config") {
        print <<'END';
graph_title FIXME TITLE
graph_args --base 1000 --lower-limit 0
graph_vlabel FIXME VLABEL
graph_category freenet
graph_info FIXME GRAPH_INFO

count.label FIXME LABEL
count.type GAUGE
count.draw LINE
count.info FIXME INFO
END
    }
    default {
        my $fcp = Net::FCP::Tiny->new(
            name => 'Freenet Munin Plugin',
            host => $ENV{FREENET_HOST},
            port => $ENV{FREENET_PORT},
        );

        my $info = $fcp->array2hash($fcp->send_msg(<<'END'));
GetNode
WithPrivate=true
WithVolatile=true
EndMessage
END
        use Data::Dump 'dump';
        say dump $info;

        #print "count.value $info->{$what}\n";
    }
}
