#!/home/v-perlbrew/perl5/perlbrew/bin/perl
use 5.010;
use strict;
use warnings;
use Net::FCP::Tiny;

given ($ARGV[0]) {
    when ("config") {
        print <<END;
graph_title Freenet Java memory use
graph_args --base 1024 --lower-limit 0
graph_vlabel bytes
graph_category freenet
graph_info The Java memory use of Freenet

maximum.label maximum
maximum.type GAUGE
maximum.draw LINE2
maximum.info Maximum Java memory use

allocated.label allocated
allocated.type GAUGE
allocated.draw LINE2
allocated.info Java allocated memory

used.label used
used.type GAUGE
used.draw LINE2
used.info Used Java memory

free.label free
free.type GAUGE
free.draw LINE2
free.info Free Java memory
END
    }
    default {
        my $fcp = Net::FCP::Tiny->new(
            name => 'Freenet Munin Plugin',
            host => $ENV{FREENET_HOST},
            port => $ENV{FREENET_PORT},
        );

        my $info = $fcp->array2hash($fcp->send_msg(<<'END'));
GetNode
WithPrivate=false
WithVolatile=true
EndMessage
END

        my %out = (
            "volatile.allocatedJavaMemory" => 'allocated',
            "volatile.freeJavaMemory"      => 'free',
            "volatile.maximumJavaMemory"   => 'maximum',
            "volatile.usedJavaMemory"      => 'used',
        );
        while (my ($var, $label) = each %out) {
            say "$label.value $info->{$var}";
        }
    }
}
