#!/home/v-perlbrew/perl5/perlbrew/bin/perl
use 5.010;
use strict;
use warnings;
use Net::FCP::Tiny;

given ($ARGV[0]) {
    when ("config") {
        print <<END;
graph_title Freenet I/O rate
graph_args --base 1024 --lower-limit 0
graph_vlabel bytes/sec
graph_category freenet
graph_info The I/O rate of Freenet in bytes per second

input.label input
input.type GAUGE
input.draw LINE
input.info Input

output.label output
output.type GAUGE
output.draw LINE
output.info Output

input_recent.label recent input
input_recent.type GAUGE
input_recent.draw LINE
input_recent.info Recent input

output_recent.label recent output
output_recent.type GAUGE
output_recent.draw LINE
output_recent.info Recent output

input_average.label average input
input_average.type GAUGE
input_average.draw LINE
input_average.info Average input over this session

output_average.label average output
output_average.type GAUGE
output_average.draw LINE
output_average.info Average output over this session
END
    }
    default {
        my $fcp = Net::FCP::Tiny->new(
            name => 'Freenet Munin Plugin',
            host => $ENV{FREENET_HOST},
            port => $ENV{FREENET_PORT},
        );

        my ($input, $output)         = (0,0);
        my ($input_rec, $output_rec) = (0,0);
        my ($input_average, $output_average) = (0,0);

        if ($fcp) {
            my $info = $fcp->array2hash($fcp->send_msg(<<'END'));
GetNode
WithPrivate=false
WithVolatile=true
EndMessage
END

            ($input, $output)         = @$info{qw(volatile.totalInputRate volatile.totalOutputRate)};
            ($input_rec, $output_rec) = map { int } @$info{qw(volatile.recentInputRate volatile.recentOutputRate)};

            my $uptime = $info->{'volatile.uptimeSeconds'};
            ($input_average, $output_average) = @$info{qw(volatile.totalInputBytes volatile.totalOutputBytes)};
            $input_average  = int($input_average / $uptime);
            $output_average = int($output_average / $uptime);
        }

        print <<"END";
input.value           $input
output.value          $output

input_recent.value    $input_rec
output_recent.value   $output_rec

input_average.value   $input_average
output_average.value  $output_average
END
    }
}
