#!/home/v-perlbrew/perl5/perlbrew/bin/perl
use 5.010;
use strict;
use warnings;
use Net::FCP::Tiny;

given ($ARGV[0]) {
    when ("config") {
        print <<END;
graph_title Freenet total I/O
graph_args --base 1024 --lower-limit 0
graph_vlabel bytes
graph_category freenet
graph_info The total I/O of Freenet in bytes for this session

input.label input
input.type GAUGE
input.draw LINE2
input.info Input

output.label output
output.type GAUGE
output.draw LINE2
output.info Output
END
    }
    default {
        my $fcp = Net::FCP::Tiny->new(
            name => 'Freenet Munin Plugin',
            host => $ENV{FREENET_HOST},
            port => $ENV{FREENET_PORT},
        );

        my $info = $fcp->array2hash($fcp->send_msg(<<'END'));
GetNode
WithPrivate=false
WithVolatile=true
EndMessage
END

        print <<"END";
input.value   $info->{'volatile.totalInputBytes'}
output.value  $info->{'volatile.totalOutputBytes'}
END
    }
}
