#!/home/v-perlbrew/perl5/perlbrew/bin/perl
use 5.010;
use strict;
use warnings;
use Net::FCP::Tiny;

given ($ARGV[0]) {
    when ("config") {
        print <<END;
graph_title Freenet Java memory use
graph_args --base 1000 -l 0
graph_vlabel freenet
graph_category 
graph_info The Java memory use of Freenet

allocated.label allocated
allocated.type GAUGE
allocated.info Java allocated memory

maximum.label maximum
maximum.type GAUGE
maximum.info Maximum Java memory use

free.label free
free.type GAUGE
free.info Free Java memory

used.label used
used.type GAUGE
used.info Used Java memory
END
    }
    default {
        my $fcp = Net::FCP::Tiny->new(
            name => 'Freenet Munin Plugin',
            host => $ENV{FREENET_HOST},
            port => $ENV{FREENET_PORT},
        );

        my $info = $fcp->array2hash($fcp->send_msg(<<'END'));
GetNode
WithPrivate=false
WithVolatile=true
EndMessage
END

        my %out = (
            "volatile.allocatedJavaMemory" => 'allocated',
            "volatile.freeJavaMemory"      => 'free',
            "volatile.maximumJavaMemory"   => 'maximum',
            "volatile.usedJavaMemory"      => 'used',
        );
        while (my ($var, $label) = each %out) {
            say "$label.value $info->{$var}";
        }
    }
}
